/* Autogenerated by png2wx.pl on Tue Mar 10 10:41:50 2020 */
#ifndef DLGBMP_H
#define DLGBMP_H 1

#include <wx/wxprec.h>
#ifndef WX_PRECOMP
#	include <wx/wx.h>
#endif

extern void dlgtest_initialize_images(void);

extern wxBitmap *_img_dlgtest;

#endif /* DLGBMP_H */
